---
title: "LCD Stations"
author: "Caroline Williams"
output:
  prettydoc::html_pretty:
    theme: leonids
    highlight: github
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Download Stations

To Do (UPDATED 10/9/20):
1. find way of accessing stations that are resulting in an error
2. Perhaps start with just one cluster to analyze than repeat for other cluster?
3. make a function

### Test 1
```{r}
library(rnoaa)
library(dplyr)
library(tidyr)
library(vctrs)
library(plyr)

# List of LCD stations and their respective station numbers
lcd_stat <- list("72511814751", # HARRISBURG CAPITAL CITY AIRPORT, PA US
                 "72511514711", # MIDDLETOWN HARRISBURG INTERNATIONAL AIRPORT, PA US
                 "99999964756", # MILLBROOK 3 W, NY US
                 "72520094823", # PITTSBURGH ASOS, PA US
                 "72503614757", # POUGHKEEPSIE AIRPORT, NY US
                 "72510314712", # READING REGIONAL AIRPORT, PA US
                 "72514014778", # SELINSGROVE PENN VALLEY AIRPORT, PA US
                 "99999954785", # SOMERSET AIRPORT, NJ US
                 "99999954793", # SUSSEX AIRPORT, NJ US
                 "72409514792", # TRENTON MERCER AIRPORT, NJ US
                 "72427514894", # WHEELING OHIO CO AIRPORT, WV US
                 "72513014777", # WILKES BARRE SCRANTON INTERNATIONAL AIRPORT, PA US
                 "72514014778", # WILLIAMSPORT REGIONAL AIRPORT, PA US
                 "99999954779", # AEROFLEX ANDOVER AIRPORT, NJ US
                 "72517014737", # ALLENTOWN LEHIGH VALLEY INTERNATIONAL AIRPORT, PA US
                 "99999954782", # HERITAGE FIELD AIRPORT, PA US
                 "99999954737", # LANCASTER AIRPORT, PA US
                 "99999954704", # NORWOOD MEMORIAL AIRPORT, MA US
                 "72510094746", # WORCESTER, MA US
                 "74410414763", # PITTSFIELD MUNICIPAL AIRPORT, MA US
                 "99999994994", # BOSCOBEL AIRPORT, WI US
                 "99999914702", # BEDFORD HANSCOM FIELD, MA US
                 "72510704780", # FITCHBURG MUNICIPAL AIRPORT, MA US
                 "72498894704", # DANSVILLE MUNICIPAL AIRPORT, NY US
                 "99999954778", # PENN YAN AIRPORT, NY US
                 "99999954768", # NORTH ADAMS HARRIMAN AIRPORT, MA US
                 "99999994723", # LAWRENCE MUNICIPAL AIRPORT, MA US
                 "72518014735", # ALBANY INTERNATIONAL AIRPORT, NY US
                 "72519014771", # SYRACUSE HANCOCK INTERNATIONAL AIRPORT, NY US
                 "72529014768", # ROCHESTER GREATER INTERNATIONAL, NY US
                 "72518514750", # GLENS FALLS AIRPORT, NY US
                 "99999954740", # SPRINGFIELD HARTNESS STATE AIRPORT, VT US
                 "99999954773", # FULTON OSWEGO CO AIRPORT, NY US
                 "99999954772", # FRYEBURG EASTERN SLOPES REGL AIRPORT, ME US
                 "72537094847", # DETROIT METRO AIRPORT, MI US
                 "99999994815", # KALAMAZOO BATTLE CREEK INTERNATIONAL AIRPORT, MI US
                 "72539514833", # JACKSON REYNOLDS FIELD, MI US
                 "72539014836", # LANSING CAPITAL CITY AIRPORT, MI US
                 "72637014826", # FLINT FCWOS, MI US
                 "72641014837", # MADISON DANE CO REGIONAL AIRPORT, WI US
                 "99999954903", # NECEDAH 5 WNW, WI US
                 "72638094814", # HOUGHTON LAKE ROSCOMMON CO AIRPORT, MI US
                 "72645014898", # GREEN BAY A S INTERNATIONAL AIRPORT, WI US
                 "72646314897", # WAUSAU ASOS, WI US
                 "72734714841", # PELLSTON REGIONAL AIRPORT, MI US
                 "99999994893", # IRON MOUNTAIN FORD AIRPORT, MI US
                 "99999994973", # HAYWARD MUNICIPAL AIRPORT, WI US
                 "72221513884", # CRESTVIEW BOB SIKES AIRPORT, FL US
                 "72216693845", # VALDOSTA REGIONAL AIRPORT, GA US
                 "99999963829", # NEWTON 11 SW, GA US
                 "99999963828", # NEWTON 8 W, GA US
                 "72216013869", # ALBANY SW GEORGIA REGIONAL AIRPORT, GA US
                 "72316013870", # ALMA BACON CO AIRPORT, GA US
                 "72207003822", # SAVANNAH INTERNATIONAL AIRPORT, GA US
                 "72225593842", # COLUMBUS METROPOLITAN AIRPORT, GA US
                 "72217003813", # MACON MIDDLE GA REGIONAL AIRPORT, GA US
                 "99999953874", # GREENWOOD CO AIRPORT, SC US
                 "99999953838", # GAINESVILLE LEE GILMER MEMORIAL AIRPORT, GA US
                 "72320093801", # ROME R B RUSSELL AIRPORT, GA US
                 "72319093846", # ANDERSON FAA AIRPORT, SC US
                 "99999953850", # CLEMSON OCONEE CO AIRPORT, SC US
                 "72311913886", # GREENVILLE DOWNTOWN AIRPORT, SC US
                 "72312003870", # GRNVL SPART INTERNATIONAL AIRPORT, SC US
                 "99999953870", # GASTONIA MUNICIPAL AIRPORT, NC US
                 "72314013881") # CHARLOTTE DOUGLAS AIRPORT, NC US

# iterate through lcd function from rnoaa package using lapply

lcd_data <- lapply(lcd_stat, function(x) {
  as_tibble(rbind.fill(lcd(x, year = 2005),
                       lcd(x, year = 2006),
                       lcd(x, year = 2007),
                       lcd(x, year = 2008),
                       lcd(x, year = 2009),
                       lcd(x, year = 2010),
                       lcd(x, year = 2011),
                       lcd(x, year = 2012),
                       lcd(x, year = 2013),
                       lcd(x, year = 2014)))
})

# Try to iterate through m_2005
#test <- as_tibble(m_2005[[1]])
#for (i in m_2005) {
#  as_tibble(i)
#  return()
#}
```

```{r}
# Finding which data is present/ absent in the 10 years of interest
# This thesis is already completed. At the time of completion all data was available for all to years
# interestingly, some data is now unavailable

lcd_stat <- list("72511814751", # all 10 years
                 "72511514711", # missing 2011-2014
                 "99999964756", # all 10 years
                 "72520094823", # all 10 years
                 "72503614757", # all 10 years
                 "72510314712", # all 10 years
                 "72514014778", # all 10 years
                 "99999954785", # missing 2006-2014
                 "99999954793", # missing 2006-2014
                 "72409514792", # all 10 years
                 "72427514894", # all 10 years
                 "72513014777", # all 10 years
                 "72514014778", # all 10 years
                 "99999954779", # missing 2006-2014?
                 "72517014737", # all 10 years
                 "99999954782", # missing 2006-2014
                 "99999954737", # missing 2006-2014
                 "99999954704", # missing 2006-2014
                 "72510094746", # missing 2008
                 "74410414763", # missing 2005
                 "99999994994", # missing all 10 years
                 "99999914702", # missing 2006-2014
                 "72510704780", # all 10 years
                 "72498894704", # all 10 years
                 "99999954778", # missing 2006-2014
                 "99999954768", # missing 2006-2014
                 "99999994723", # missing 2006-2014
                 "72518014735", # all 10 years
                 "72519014771", # all 10 years
                 "72529014768", # all 10 years
                 "72518514750", # missing 2011-2014
                 "99999954740", # missing 2006-2014
                 "99999954773", # missing 2006-2014
                 "99999954772", # missing 2006-2014
                 "72537094847", # all 10 years
                 "99999994815", # missing 2006-2014
                 "72539514833", # all 10 years
                 "72539014836", # all 10 years
                 "72637014826", # all 10 years
                 "72641014837", # all 10 years
                 "99999954903", # all 10 years
                 "72638094814", # all 10 years
                 "72645014898", # all 10 years
                 "72646314897", # all 10 years
                 "72734714841", # all 10 years
                 "99999994893", # missing 2006-2014
                 "99999994973", # missing 2006-2014
                 "72221513884", # missing 2006-2014
                 "72216693845", # all 10 years
                 "99999963829", # all 10 years
                 "99999963828", # all 10 years
                 "72216013869", # all 10 years
                 "72316013870", # missing 2008
                 "72207003822", # all 10 years
                 "72225593842", # all 10 years
                 "72217003813", # all 10 years
                 "99999953874", # missing 2006-2014
                 "99999953838", # missing 2006-2014
                 "72320093801", # all 10 years
                 "72319093846", # missing 2008
                 "99999953850", # missing 2006-2014
                 "72311913886", # all 10 years
                 "72312003870", # all 10 years
                 "99999953870", # missing 2006-2014
                 "72314013881") # all 10 years

# testing one file for all ten years

m_worcester <- lapply("72510094746", function(x) {
  lcd(x, year = 2005, 2006, 2007, 2008, 2009, 2010, 2011, 2012, 2013, 2014)
})
```
### Test 1.b
```{r}
library(rnoaa)
library(dplyr)
library(tidyr)
library(vctrs)
library(plyr)

# List of LCD stations and their respective station numbers
lcd_stat <- list("72511814751", # HARRISBURG CAPITAL CITY AIRPORT, PA US
                 "99999964756", # MILLBROOK 3 W, NY US
                 "72520094823", # PITTSBURGH ASOS, PA US
                 "72503614757", # POUGHKEEPSIE AIRPORT, NY US
                 "72510314712", # READING REGIONAL AIRPORT, PA US
                 "72514014778", # SELINSGROVE PENN VALLEY AIRPORT, PA US
                 "72409514792", # TRENTON MERCER AIRPORT, NJ US
                 "72427514894", # WHEELING OHIO CO AIRPORT, WV US
                 "72513014777", # WILKES BARRE SCRANTON INTERNATIONAL AIRPORT, PA US
                 "72514014778", # WILLIAMSPORT REGIONAL AIRPORT, PA US
                 "72517014737", # ALLENTOWN LEHIGH VALLEY INTERNATIONAL AIRPORT, PA US
                 "72510704780", # FITCHBURG MUNICIPAL AIRPORT, MA US
                 "72498894704", # DANSVILLE MUNICIPAL AIRPORT, NY US
                 "72518014735", # ALBANY INTERNATIONAL AIRPORT, NY US
                 "72519014771", # SYRACUSE HANCOCK INTERNATIONAL AIRPORT, NY US
                 "72529014768", # ROCHESTER GREATER INTERNATIONAL, NY US
                 "72537094847", # DETROIT METRO AIRPORT, MI US
                 "72539514833", # JACKSON REYNOLDS FIELD, MI US
                 "72539014836", # LANSING CAPITAL CITY AIRPORT, MI US
                 "72637014826", # FLINT FCWOS, MI US
                 "72641014837", # MADISON DANE CO REGIONAL AIRPORT, WI US
                 "99999954903", # NECEDAH 5 WNW, WI US
                 "72638094814", # HOUGHTON LAKE ROSCOMMON CO AIRPORT, MI US
                 "72645014898", # GREEN BAY A S INTERNATIONAL AIRPORT, WI US
                 "72646314897", # WAUSAU ASOS, WI US
                 "72734714841", # PELLSTON REGIONAL AIRPORT, MI US
                 "72216693845", # VALDOSTA REGIONAL AIRPORT, GA US
                 "99999963829", # NEWTON 11 SW, GA US
                 "99999963828", # NEWTON 8 W, GA US
                 "72216013869", # ALBANY SW GEORGIA REGIONAL AIRPORT, GA US
                 "72207003822", # SAVANNAH INTERNATIONAL AIRPORT, GA US
                 "72225593842", # COLUMBUS METROPOLITAN AIRPORT, GA US
                 "72217003813", # MACON MIDDLE GA REGIONAL AIRPORT, GA US
                 "72320093801", # ROME R B RUSSELL AIRPORT, GA US
                 "72311913886", # GREENVILLE DOWNTOWN AIRPORT, SC US
                 "72312003870", # GRNVL SPART INTERNATIONAL AIRPORT, SC US
                 "72314013881") # CHARLOTTE DOUGLAS AIRPORT, NC US

# iterate through lcd function from rnoaa package using lapply

lcd_data <- lapply(lcd_stat, function(x) {
  as_tibble(rbind.fill(lcd(x, year = 2005),
                       lcd(x, year = 2006),
                       lcd(x, year = 2007),
                       lcd(x, year = 2008),
                       lcd(x, year = 2009),
                       lcd(x, year = 2010),
                       lcd(x, year = 2011),
                       lcd(x, year = 2012),
                       lcd(x, year = 2013),
                       lcd(x, year = 2014)))
})

# Try to iterate through m_2005
#test <- as_tibble(m_2005[[1]])
#for (i in m_2005) {
#  as_tibble(i)
#  return()
#}
```

## Test 2
```{r}
# Here is a test example of looping through stations for all 10 years
# The output is a list of three tibbles corresponding to each input station
stat_name <- list("HARRISBURG_CAPITAL_CITY_AIRPORT_PA",
                  "MILLBROOK_3_W_NY",
                  "PITTSBURGH ASOS_PA")
                 
lcd_test <- list("72511814751", 
                 "99999964756", 
                 "72520094823")

m_test <- function (x, fun){ 
  if (fun == "download")
    lapply(x, function (x) {
      as_tibble(rbind.fill(lcd(x, year = 2005),
                           lcd(x, year = 2006),
                           lcd(x, year = 2007),
                           lcd(x, year = 2008),
                           lcd(x, year = 2009),
                           lcd(x, year = 2010),
                           lcd(x, year = 2011),
                           lcd(x, year = 2012),
                           lcd(x, year = 2013),
                           lcd(x, year = 2014)))
})}
m_test(lcd_test, "download")
# Considering using paste0 to name each tibble somehow
t <- m_test[[1]]
paste0("LCD_", stat_name[[1]], "_2005_2014")

# Trying different methods of sorting data
# To DO: try using pivot_wider to split date into year and month
# then calculate the mean ofjuly over the 10 years per station
# output to a single tibble file

LCD_new <- as_tibble(m_test[[1]]) 
LCD_new %>% select(station, date, latitude, longitude, elevation, name, monthlymaximumtemperature, monthlymeantemperature,monthlyminimumtemperature) %>% arrange(monthlymaximumtemperature, monthlymeantemperature,monthlyminimumtemperature)

LCD_new %>% select(station, date, latitude, longitude, elevation, name, monthlymaximumtemperature, monthlymeantemperature,monthlyminimumtemperature) %>% arrange(desc(date))

LCD_degrees <- LCD_new %>% select(station, date, latitude, longitude, elevation, name, monthlymaximumtemperature, monthlymeantemperature,monthlyminimumtemperature) %>% filter(monthlymeantemperature > 0)

LCD_degrees %>% summarize_all(mean(monthlymaximumtemperature, monthlymeantemperature,monthlyminimumtemperature))
```

