---
author: "Caroline Williams"
title: "Overview"
output:
  prettydoc::html_pretty:
    theme: leonids
    highlight: github
vignette: >
  %\VignetteIndexEntry{Overview}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Overview
This package is divided into the following vignettes:
  
  1. LCD_stations.Rmd
  2. NLCD_raster.Rmd
  3. Window_Analysis.Rmd

The purpose of this package is to recreate my senior honors thesis on examining the relationship between local near surface temperature and fores cover. Additional handover types are examined to help explain the influence of other land cover types nearby with temperature also.

## LCD Stations
This vignette includes downloading meteorological station data using the rnoaa package. The data was then sorted and cleaned up for later use.

## NLCD Raster
The land cover data was downloaded for 10 years and the cropped to the extents of each cluster created in LCD Stations. This was to facilitate processing in the analysis.

## Window Analysis
The RpyGeo package was used to window to 990 m by 990 m box around each station to then produce area and statistics between the two variables, temperature and land cover.
