---
title: "Window Analysis"
author: "Caroline Williams"
output:
  prettydoc::html_pretty:
    theme: leonids
    highlight: github
vignette: >
  %\VignetteIndexEntry{Window Analysis}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Arcpy Testing 
```{r}
library(RPyGeo)
rpygeo_build_env(path = "C:/Program Files/ArcGIS/Pro/bin/Python/envs/arcgispro-py3/")
```

## Find arcpy functions
```{r, eval = FALSE}
rpygeo_help(arcpy_function = "arcpy.gp.ExtractByMask_sa")
```

## Import Libraries
```{python}
import arcpy
from arcpy import env
from arcpy.sa import *
```

# Set Environment
```{python}
# set workspace
env.workspace = "D:/"

# set, extent, coordinate system, and overwrite options
env.extent = r"D:/r_outputs/nlcd_2005_crop.tif"
env.outputCoordinateSystem = r"r_outputs/NE1_pts.shp"
env.snapRaster = r"D:/r_outputs/nlcd_2005_crop.tif"
env.overwriteOutput = "TRUE"
```

# Create Buffer around Stations
```{python}
# buffer 495 m around station points
arcpy.Buffer_analysis(in_features = "r_outputs/NE1_pts.shp", out_feature_class = "python_outputs/NE1_495buff.shp", buffer_distance_or_field = "495 Meters", line_side = "FULL", line_end_type = "ROUND", dissolve_option = "NONE", dissolve_field = "", method = "PLANAR")

# create window around stations using buffer output
arcpy.FeatureEnvelopeToPolygon_management(in_features="python_outputs/NE1_495buff.shp", out_feature_class="python_outputs/NE1_window.shp", single_envelope="SINGLEPART")

# Polygon to Raster
arcpy.conversion.PolygonToRaster("D:/python_outputs/NE1_window.shp", "ORIG_FID", "D:/python_outputs/NE1_window_raster.tif", "CELL_CENTER", "NONE", 30)

# extract by mask for each year
NE1_2005_window = ExtractByMask("/data/landcover_2005_vote.tif", "D:/python_outputs/NE1_window_raster.tif")

NE1_2005_window.save("D:/python_outputs/NE1_2005_window.tif")

# convert
outInt = Int("D:/python_outputs/NE1_window_raster.tif")
outInt.save("D:/python_outputs/NE1_window_raster_int.tif")

# tabulate area for each year
TabulateArea("D:/python_outputs/NE1_window_raster.tif", "VALUE", "D:/python_outputs/NE1_2005_window.tif", "VALUE", "D:/python_outputs/area2005..csv", 30)
```

## Load python outputs
```{r}
NE1_495buff <- rpygeo_load("D:/python_outputs/NE1_495buff.shp")

NE1_window <- rpygeo_load("D:/python_outputs/NE1_window.shp")

NE1_2005_window <- rpygeo_load("D:/python_outputs/NE1_2005_window.tif")

NE1_window_raster <- rpygeo_load("D:/python_outputs/NE1_window_raster.tif")

area2005 <- foreign::read.dbf("D:/python_outputs/area2005.dbf")
```

## Sort data
```{r}
area2005 <- area2005 %>% rename(ORIG_FID = VALUE)
```

## Join Tables by Clusters
```{r}
NE1_cluster <- dplyr::full_join(NE1_window, area2005, by = "ORIG_FID")
```

## Rename Columns
```{r}
NE1_cluster <- NE1_cluster %>% rename(
  open_water = VALUE_11, 
  deve_open = VALUE_21, 
  deve_low = VALUE_22, 
  deve_med = VALUE_23, 
  deve_high = VALUE_24, 
  barren = VALUE_31, 
  decid_for = VALUE_41, 
  ever_for = VALUE_42, 
  scrub = VALUE_52, 
  grassland = VALUE_71, 
  pasture = VALUE_81, 
  crop = VALUE_82, 
  woody_wet = VALUE_90, 
  emer_herb_wet = VALUE_95)
```

## Calculate %
```{r}
# calculate total area and lc percent
NE1_cluster <- NE1_cluster %>% 
  mutate(area_m = (open_water + deve_open +
                     deve_low + 
        deve_med + deve_high + barren + 
        decid_for + ever_for + scrub + 
        grassland + pasture + crop + 
        woody_wet + emer_herb_wet)) %>% mutate(
  water_perc = (open_water / area_m) * 100,
  deve_open_perc = (deve_open / area_m) * 100, 
  deve_low_perc = (deve_low / area_m) * 100, 
  deve_med_perc = (deve_med / area_m) * 100, 
  deve_high_perc = (deve_high / area_m) * 100, 
  barren_perc = (barren / area_m) * 100, 
  decid_for_perc = (decid_for / area_m) * 100, 
  ever_for_perc = (ever_for / area_m) * 100, 
  scrub_perc = (scrub / area_m) * 100, 
  grass_perc = (grassland / area_m) * 100, 
  pasture_perc = (pasture / area_m) * 100, 
  crop_perc = (crop / area_m) * 100, 
  woody_wet_perc = (woody_wet / area_m) * 100, 
  emerherbwet_perc = (emer_herb_wet / area_m) * 100)

NE1_map <- NE1_cluster %>% mutate(fc_perc = (decid_for_perc + ever_for_perc) / 2)
```

To Do:
- repeat process for 2006 to 2014 and average land cover at stations over time
  - temperature is already averaged
- then repeat for remaining clusters
